set(MGMC_SOURCE_FILES ${MGMC_SOURCE_FILES}
  src/material.cpp
  src/mg_nuclide.cpp
  src/mg_angle_distribution.cpp
  src/legendre_distribution.cpp
  src/nuclide.cpp
  src/surface_tracker.cpp
  src/delta_tracker.cpp
  src/carter_tracker.cpp
  src/implicit_leakage_delta_tracker.cpp
  src/transporter.cpp
  src/approximate_mesh_cancelator.cpp
  src/basic_exact_mg_cancelator.cpp
  src/exact_mg_cancelator.cpp
  src/cell_search_mesh.cpp
  src/cancelator.cpp
  src/noise.cpp
  src/branchless_power_iterator.cpp
  src/power_iterator.cpp
  src/fixed_source.cpp
  src/modified_fixed_source.cpp
  src/noise_maker.cpp
  src/square_oscillation_noise_source.cpp
  src/flat_vibration_noise_source.cpp
  src/source.cpp
  src/particle.cpp
  src/spatial_distribution.cpp
  src/box.cpp
  src/point.cpp
  src/direction_distribution.cpp
  src/isotropic.cpp
  src/mono_directional.cpp
  src/cone.cpp
  src/energy_distribution.cpp
  src/mono_energetic.cpp
  src/tallies.cpp
  src/mesh_tally.cpp
  src/source_mesh_tally.cpp
  src/collision_mesh_tally.cpp
  src/track_length_mesh_tally.cpp
  src/parser.cpp
  src/simulation.cpp
  src/slice_plot.cpp
  src/pixel.cpp
  src/plotter.cpp
  src/hex_lattice.cpp
  src/rect_lattice.cpp
  src/lattice.cpp
  src/lattice_universe.cpp
  src/cell_universe.cpp
  src/universe.cpp
  src/output.cpp
  src/geometry.cpp
  src/cell.cpp
  src/sphere.cpp
  src/zcylinder.cpp
  src/ycylinder.cpp
  src/xcylinder.cpp
  src/plane.cpp
  src/zplane.cpp
  src/yplane.cpp
  src/xplane.cpp
  src/surface.cpp
  src/error.cpp
  src/mpi.cpp
  src/settings.cpp
  src/header.cpp
  src/rng.cpp
)
