set(MGMC_SOURCE_FILES ${MGMC_SOURCE_FILES}
  src/surface_tracker.cpp
  src/delta_tracker.cpp
  src/carter_tracker.cpp
  src/cancel_bin.cpp
  src/power_iterator.cpp
  src/tallies.cpp
  src/const_material.cpp
  src/flux_tally.cpp
  src/power_tally.cpp
  src/parser.cpp
  src/slice_plot.cpp
  src/pixel.cpp
  src/plotter.cpp
  src/hex_lattice.cpp
  src/rect_lattice.cpp
  src/lattice.cpp
  src/lattice_universe.cpp
  src/cell_universe.cpp
  src/universe.cpp
  src/timer.cpp
  src/output.cpp
  src/geometry.cpp
  src/cell.cpp
  src/sphere.cpp
  src/zcylinder.cpp
  src/ycylinder.cpp
  src/xcylinder.cpp
  src/plane.cpp
  src/zplane.cpp
  src/yplane.cpp
  src/xplane.cpp
  src/surface.cpp
  src/direction.cpp
  src/position.cpp
  src/vector.cpp
  src/error.cpp
)